### ISSUE TITLE
Main GDS documentation should be here

### ISSUE THREAD

**Issue by dr-shorthair** [CSIRO-enviro-informatics/geometry-data-service#19]
The documentation at loci.cat https://github.com/CSIRO-enviro-informatics/loci.cat/blob/gh-pages/geometry-data-service.md shoudl just be a summary and xrefs to the main GDS documentation here. GDS is a standalone spec which merits a life on its own merits.

**Comment by jyucsiro** [comment]
@dr-shorthair i've created the `gh-pages` branch (https://github.com/CSIRO-enviro-informatics/geometry-data-service/tree/gh-pages) to stick doco purely about GDS (rather than the README.md in master, which is about using GDS).

The reason for this is that 
a) It's cleaner (no code in the branch)
b) I have a docker continuous build happening on master and dev so any doco changes triggers the docker build process which isn't needed 

I've turned on GH pages for this repo so you can access content at http://csiro-enviro-informatics.github.io/geometry-data-service

So if we add content via the `gh-pages` branch, we can also manage it using Github PRs as an added bonus.
